#version: "3.8"

services:
  redis:
    image: redis:8.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: ./app
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  consumer:
    build: ./app
    container_name: log-consumer
    depends_on:
      - redis
    volumes:
      - ./app:/app
    command: python log_consumer.py

volumes:
  redis_data:
